CREATE TABLE bank_operation (
  id bigint generated by default as identity primary key,
  account_number varchar(64) not null,
  operation_time timestamp not null,
  beneficiary varchar(255) not null,
  operation_comment varchar(1024),
  amount decimal(19, 2) not null,
  currency varchar(8) not null
);

create index idx_bank_operation_acc_time
  on bank_operation(account_number, operation_time);
